### ISSUE TITLE
tkinter.TclError: cannot use geometry manager pack inside... slaves managed by grid

### ISSUE THREAD

**Issue by jgill-arista** [russellkelly/BGPFlowspecPolicyManager#1]
Hey Russell!

Something suddenly caused this code to break recently, maybe a python2 or tkinter change.

I commented out line 1318 and 1433, and it seems to be happy.

https://github.com/russellkelly/BGPFlowspecPolicyManager/blob/c6241de2b750d06cf9311a0be3d0528de92a9804/FlowspecPolicyManager.py#L1318

https://github.com/russellkelly/BGPFlowspecPolicyManager/blob/c6241de2b750d06cf9311a0be3d0528de92a9804/FlowspecPolicyManager.py#L1433

The traceback seen when running BGPFlowspecPolicyManager.py:
```
Traceback (most recent call last):
  File "FlowspecPolicyManager.py", line 3438, in <module>
    gui = FlowspecGUI(root, SflowQueue,FlowRouteQueueForQuit,FlowRouteQueue,UpdatePolicyQueue,SignalResetQueue)
  File "FlowspecPolicyManager.py", line 1194, in __init__
    self.createWidgets(BG0, BG1)
  File "FlowspecPolicyManager.py", line 1433, in createWidgets
    ProgrammedPolicyLabel.pack()
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1951, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside .140246952039200.140246952039416.140246952040064.140246952040568 which already has slaves managed by grid
```

Python 2.7.16
package:
Name         : python2-tkinter
Version      : 2.7.16
Release      : 12.module_el8.1.0+219+cf9e6ac9

**Comment by russell-arrcus** [comment]
Thanks John!  Yeah I guess I shouldn't mix pack() with grid.  Removed those entries.
