### ISSUE TITLE
fix typo in remote as

### ISSUE THREAD

**Issue by noredistribution** [russellkelly/BGPFlowspecPolicyManager#2]
In line 75 it says `remote_as` instead of `remote-as`
https://github.com/russellkelly/BGPFlowspecPolicyManager/blob/c6241de2b750d06cf9311a0be3d0528de92a9804/JinjaTemplates/EdgeRouterConfigs.j2#L75

**Comment by russellkelly** [comment]
Cheers Tamas

Fixed in 

https://github.com/russellkelly/BGPFlowspecPolicyManager/commit/b00b38a37d7cd58386dacb3fffbb72069f3ed4f9
